name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify
        env:
          FORCE_PYTHON: "1"
        run: ./scripts/verify.sh
